image: php:7.4

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git zip unzip
  - curl -sS https://getcomposer.org/installer | php
  - rm composer.lock
  - php composer.phar install

static_analysis:
  stage: static_analysis
  script:
    - vendor/bin/phpstan analyse -c phpstan-gitlab.neon --error-format=gitlab --memory-limit 1G

artifact_php72:
  stage: artifacts
  script:
    - cp -R public artifact_72
    - vendor/bin/rector process --config rector-downgrade-72.php
  artifacts:
    paths:
      - artifact_72

stages:
  - static_analysis
  - artifacts

