image: php:7.4

cache:
  paths:
    - vendor/

static_analysis:
  stage: static_analysis
  script:
    - apt-get update -yqq
    - apt-get install -yqq git zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - rm composer.lock
    - rm composer.json
    - php composer.phar require phpstan/phpstan
    - php composer.phar install
    - vendor/bin/phpstan analyse -c phpstan-gitlab.neon --error-format=gitlab --memory-limit 1G

artifacts:
  stage: artifacts
  only:
    refs:
      - master
      - develop
    changes:
      - public/**/*
      - rector.php
      - rector-downgrade-72.php
      - composer.json
      - .gitlab-ci.yml
  script:
    - apt-get update -yqq
    - apt-get install -yqq git
    - mkdir -p php74-$CI_COMMIT_REF_NAME
    - cp -r public/* php74-$CI_COMMIT_REF_NAME
    - curl -sS https://getcomposer.org/installer | php
    - rm composer.lock
    - rm composer.json
    - php composer.phar require rector/rector
    - php composer.phar install
    - vendor/bin/rector process --config rector-downgrade-72.php
    - mkdir -p php72-php73-$CI_COMMIT_REF_NAME
    - cp -r public/* php72-php73-$CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - php72-php73-$CI_COMMIT_REF_NAME
      - php74-$CI_COMMIT_REF_NAME

deploy_artifacts:
  stage: files_upload
  image: ubuntu
  only:
    refs:
      - master
      - develop
    changes:
      - public/**/*
      - rector.php
      - rector-downgrade-72.php
      - composer.json
      - .gitlab-ci.yml
  except:
    refs:
      - merge_requests
  before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git zip sshpass rsync --fix-missing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SCRIPTS_REPO" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DOMAIN_SCRIPTS_REPO >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "gitlabci-$CI_PROJECT_NAME@robotess.net"
    - git config --global user.name "Gitlab Runner ($CI_PROJECT_NAME)"
  script:
    - mkdir -p repo
    - echo "Pulling external repo into build"
    - ssh git@$DOMAIN_SCRIPTS_REPO
    - git clone git@$DOMAIN_SCRIPTS_REPO:$URL_SCRIPTS_REPO repo
    - mkdir -p repo/static/files/$CI_PROJECT_NAME
    - zip -r php74-$CI_COMMIT_REF_NAME.zip php74-$CI_COMMIT_REF_NAME
    - cp php74-$CI_COMMIT_REF_NAME.zip repo/static/files/$CI_PROJECT_NAME
    - zip -r php72-php73-$CI_COMMIT_REF_NAME.zip php72-php73-$CI_COMMIT_REF_NAME
    - cp php72-php73-$CI_COMMIT_REF_NAME.zip repo/static/files/$CI_PROJECT_NAME
    - cd repo
    - git add -f static/files/$CI_PROJECT_NAME/*.zip
    - git commit -m "Uploaded artifacts from http://gitlab.com/$CI_PROJECT_PATH/commit/$CI_COMMIT_SHA" || echo "No changes, nothing to commit!"
    - git push origin master

deploy_readme:
  stage: files_upload
  image: ubuntu
  only:
    refs:
      - master
    changes:
      - "README.md"
      - .gitlab-ci.yml
  before_script:
    - apt-get update -y && apt-get install -yqqf openssh-client git sshpass rsync --fix-missing
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SCRIPTS_REPO" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DOMAIN_SCRIPTS_REPO >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "gitlabci-$CI_PROJECT_NAME@robotess.net"
    - git config --global user.name "Gitlab Runner ($CI_PROJECT_NAME)"
  script:
    - mkdir -p repo
    - echo "Pulling external repo into build"
    - ssh git@$DOMAIN_SCRIPTS_REPO
    - git clone git@$DOMAIN_SCRIPTS_REPO:$URL_SCRIPTS_REPO repo
    - awk -v RS='---' -v ORS='---' 'NR==1{print} NR==2{print; printf"\n";exit}' repo/content/projects/$CI_PROJECT_NAME/_index.md >> _index.md
    - rm repo/content/projects/$CI_PROJECT_NAME/_index.md
    - mv _index.md repo/content/projects/$CI_PROJECT_NAME/
    - ls repo/content/projects/$CI_PROJECT_NAME/
    - sed '1d' README.md >> repo/content/projects/$CI_PROJECT_NAME/_index.md
    - cd repo
    - git add -f content/projects/$CI_PROJECT_NAME/_index.md
    - git commit -m "Uploaded README from http://gitlab.com/$CI_PROJECT_PATH/commit/$CI_COMMIT_SHA" || echo "No changes, nothing to commit!"
    - git push origin master

stages:
  - static_analysis
  - artifacts
  - files_upload