image: php:7.4

cache:
  paths:
    - vendor/

static_analysis:
  stage: static_analysis
  script:
    - apt-get update -yqq
    - apt-get install -yqq git zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - rm composer.lock
    - rm composer.json
    - cp composer-gitlab.json composer.json
    - php composer.phar install
    - vendor/bin/phpstan analyse -c phpstan-gitlab.neon --error-format=gitlab --memory-limit 1G

artifact_php72:
  stage: artifacts
  only:
    refs:
      - master
      - develop
  script:
    - composer require rector/rector --dev
    - vendor/bin/rector process --config rector-downgrade-72.php
  artifacts:
    paths:
      - listing-admin_php72

stages:
  - static_analysis
  - artifacts

