image: php:7.4

cache:
  paths:
    - vendor/

static_analysis:
  stage: static_analysis
  script:
    - apt-get update -yqq
    - apt-get install -yqq git zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - rm composer.lock
    - rm composer.json
    - php composer.phar require phpstan/phpstan
    - php composer.phar install
    - vendor/bin/phpstan analyse -c phpstan-gitlab.neon --error-format=gitlab --memory-limit 1G

artifacts_php72:
  stage: artifacts
  only:
    refs:
      - master
      - develop
  script:
    - apt-get update -yqq
    - apt-get install -yqq git zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - rm composer.lock
    - rm composer.json
    - php composer.phar require rector/rector
    - php composer.phar install
    - vendor/bin/rector process --config rector-downgrade-72.php
    - zip -r listing-admin-php72-php-73-$CI_COMMIT_REF_NAME.zip public
  artifacts:
    paths:
      - listing-admin-php72-php-73-$CI_COMMIT_REF_NAME.zip

deploy_artifacts:
  stage: deploy_artifacts
  image: ubuntu
  only:
    refs:
      - master
      - develop
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER_NAME@$SSH_SERVER "ls -lah; touch test.txt"

stages:
  - static_analysis
  - artifacts
  - deploy_artifacts