image: php:7.2

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git zip unzip
  - curl -sS https://getcomposer.org/installer | php
  - rm composer.lock
  - php composer.phar install

static_analysis:
  stage: static_analysis
  script:
    - vendor/bin/phpstan analyse -c phpstan.neon --error-format=gitlab --memory-limit 1G

stages:
  - static_analysis