version: '3'

services:
  apache:
    container_name: ladmin-php-apache
    image: ladmin-php7-apache
    build: docker
    ports:
      - 8041:80
      - 9001:9001
    depends_on:
      - mysql
      - mailhog
    links:
      - mysql
    volumes:
      - ./public:/app/public
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./phpstan.neon:/app/phpstan.neon
      - ./phpstan-baseline.neon:/app/phpstan-baseline.neon
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/configs/jac.inc.php:/app/public/samplefl/jac.inc.php:ro
      - ./docker/configs/jac.inc.php:/app/public/samplecollective/jac.inc.php:ro
      - ./docker/configs/rats.inc.php:/app/public/admin/rats.inc.php:ro
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.210.1 remote_enable=1 remote_port=9002"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - internal

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bambino
      MYSQL_USER: listingadmin
      MYSQL_PASSWORD: password
    ports:
      - 13306:3306
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - internal

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8011:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.210.0/28
